name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Use Node.js 24
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Cache PNPM store
        uses: actions/cache@v6
        with:
          path: |
            ~/.pnpm-store/v11
          key: ${{ runner.os }}-pnpm

      - name: Setup PNPM
        uses: pnpm/action-setup@v6
        with:
          version: 11.3.0
          run_install: true

      - run: pnpm run build

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: "build"

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
